# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Modified from original by Naupaka Zimmerman nzimmerman@usfca.edu

language: r
r: bioc-release
os: linux
dist: focal
cache: packages
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libgdal-dev libudunits2-dev libprotobuf-dev libjq-dev protobuf-compiler
env:
  global:
    - LINTR_COMMENT_BOT=false
    - GITHUB_PAT=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
r_github_packages:
  - jimhester/lintr
  - leffj/mctoolsr
script:
  - for file in $(find . -type f -name "*.sh"); do shellcheck $file; done;
  - R -f tests/render_rmds.R
