# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Modified from original by Naupaka Zimmerman nzimmerman@usfca.edu

language: r
r: bioc-release
os: linux
dist: focal
cache: packages
env:
  global:
    - LINTR_COMMENT_BOT=false
    - GITHUB_PAT=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
r_github_packages:
  - jimhester/lintr
  - leffj/mctoolsr
script:
  - for file in $(find . -type f -name "*.sh"); do shellcheck $file; done;
  - R -f tests/render_rmds.R
